name: Backend CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      # Checkout Code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Set up Java
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Build Project
      - name: Build Project
        run: mvn clean package

      # Run Tests
      - name: Run Tests
        run: mvn test

      # Upload Build Artifact
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: build-artifact
          path: target/*.jar

  deploy:
    name: Deploy to Staging
    runs-on: ubuntu-latest
    needs: test

    steps:
      # Checkout Code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Download Build Artifact
      - name: Download Build Artifact
        uses: actions/download-artifact@v3
        with:
          name: build-artifact
          path: target

      # Echo Deployment Message (statt echter Deployment-Schritte)
      - name: Echo Deployment Message
        run: echo "Deploying to Staging Environment"
        env:
          API_KEY: ${{ secrets.API_KEY }}
